### ISSUE TITLE
19.03.2019. Замечания по лабораторной 1

### ISSUE THREAD

**Issue by vekrasikov** [nuronbeck/subject_Project_practice#1]
Необходимо описать результаты, как указано во введении к лабораторным.
https://stepik.org/lesson/212655/step/1?unit=185868

Разработанные АПИ должны быть доступны по человекочитаемым path. Без указания расширения файлов ("*.php" встречаться в path не должно).

В коде не должны присутствовать SQL запросы. 
https://stepik.org/lesson/212333/step/1?unit=185554

Вынести свойства для подключения к базе данных в отдельный файл. Для соединения брать значения из файла со свойствами.

**Comment by nuronbeck** [comment]
Здравствуйте! Можете мою первую лабораторную проверить, исправил в соответствии с Вашими замечаниями))
